# Envoy templating values
global:
  appName: "tracker-simulator-envoy"
  networkHost: "10.0.0.16"
  envoy:
    host: "10.0.0.16"
    serviceType: LoadBalancer
    envoyPorts: 
      trackerServerPort: 31346
      trackerServerGrpcPort: 30548
      trackerClientPort: 32712
      trackerAnalyticsPort: 30313
      communicationsAppPort: 32326
    appPorts: 
      trackerServerPort: 8088
      trackerServerGrpcPort: 9003
      trackerClientPort: 8089
      trackerAnalyticsPort: 5050
      communicationsAppPort: 80
