apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: eg
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  parametersRef:
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    name: custom-proxy-config
    namespace: envoy-gateway-system
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: bare-metal-gateway
  namespace: default
spec:
  gatewayClassName: eg
  listeners:
  - name: tracker-client
    protocol: TCP
    port: {{ .Values.global.envoy.appPorts.trackerClientPort }}
  - name: tracker
    protocol: TCP
    port: {{ .Values.global.envoy.appPorts.trackerServerPort }}
  - name: tracker-grpc
    protocol: TCP
    port: {{ .Values.global.envoy.appPorts.trackerServerGrpcPort }}
  - name: tracker-analytics
    protocol: TCP
    port: {{ .Values.global.envoy.appPorts.trackerAnalyticsPort }}
  - name: communications-app
    protocol: TCP
    port: {{ .Values.global.envoy.appPorts.communicationsAppPort }} 
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: tracker-client-route
  namespace: default
spec:
  parentRefs:
  - name: bare-metal-gateway
    sectionName: tracker-client
  rules:
  - backendRefs:
    - name: trackerclient
      port: {{ .Values.global.envoy.appPorts.trackerClientPort }}
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: tracker-route
  namespace: default
spec:
  parentRefs:
  - name: bare-metal-gateway
    sectionName: tracker
  rules:
  - backendRefs:
    - name: tracker
      port: {{ .Values.global.envoy.appPorts.trackerServerPort }}
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: tracker-route-9003
  namespace: default
spec:
  parentRefs:
  - name: bare-metal-gateway
    sectionName: tracker-grpc
  rules:
  - backendRefs:
    - name: tracker
      port: {{ .Values.global.envoy.appPorts.trackerServerGrpcPort }}
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: tracker-analytics-route
  namespace: default
spec:
  parentRefs:
  - name: bare-metal-gateway
    sectionName: tracker-analytics
  rules:
  - backendRefs:
    - name: trackeranalytics
      port: {{ .Values.global.envoy.appPorts.trackerAnalyticsPort }}
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: communications-app-route
  namespace: default
spec:
  parentRefs:
  - name: bare-metal-gateway
    sectionName: communications-app
  rules:
  - backendRefs:
    - name: communications-app
      port: {{ .Values.global.envoy.appPorts.communicationsAppPort }}            
---
{{ if eq .Values.global.envoy.serviceType "NodePort" }}
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: custom-proxy-config
  namespace: envoy-gateway-system
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        type: {{ .Values.global.envoy.serviceType }}
        externalTrafficPolicy: Cluster
        patch:
          type: StrategicMerge
          value:
            spec:
              ports:
              - name: tracker-client
                nodePort: {{ .Values.global.envoy.envoyPorts.trackerClientPort }}
                port: {{ .Values.global.envoy.appPorts.trackerClientPort }}
                protocol: TCP
              - name: tracker
                nodePort: {{ .Values.global.envoy.envoyPorts.trackerServerPort }}
                port: {{ .Values.global.envoy.appPorts.trackerServerPort }}
                protocol: TCP
              - name: tracker-grpc
                nodePort: {{ .Values.global.envoy.envoyPorts.trackerServerGrpcPort }}
                port: {{ .Values.global.envoy.appPorts.trackerServerGrpcPort }}
                protocol: TCP
              - name: tracker-analytics
                nodePort: {{ .Values.global.envoy.envoyPorts.trackerAnalyticsPort }}
                port: {{ .Values.global.envoy.appPorts.trackerAnalyticsPort }}
                protocol: TCP
              - name: communications-app
                nodePort: {{ .Values.global.envoy.envoyPorts.communicationsAppPort }}
                port: {{ .Values.global.envoy.appPorts.communicationsAppPort }}
                protocol: TCP
{{ else if eq .Values.global.envoy.serviceType "LoadBalancer" }}
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: custom-proxy-config
  namespace: envoy-gateway-system
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        type: LoadBalancer
        externalTrafficPolicy: Cluster
{{ end }}                
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: tracker-least-connections-8088
  namespace: default
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: TCPRoute
    name: tracker-route
  loadBalancer:
    type: LeastRequest
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: tracker-least-connections-9003
  namespace: default
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: TCPRoute
    name: tracker-route-9003
  loadBalancer:
    type: LeastRequest  